/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForProvidersRouteImport } from './routes/for-providers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as ProfileProfileIdRouteImport } from './routes/profile.$profileId'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AccountRequestsRouteImport } from './routes/account.requests'
import { Route as AccountFavoritesRouteImport } from './routes/account.favorites'

const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProvidersRoute = ForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIdRoute = ProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRequestsRoute = AccountRequestsRouteImport.update({
  id: '/account/requests',
  path: '/account/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/account/favorites',
  path: '/account/favorites',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/for-providers': typeof ForProvidersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/provider': typeof ProviderRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/requests': typeof AccountRequestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/for-providers': typeof ForProvidersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/provider': typeof ProviderRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/requests': typeof AccountRequestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/for-providers': typeof ForProvidersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/provider': typeof ProviderRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/requests': typeof AccountRequestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/$profileId': typeof ProfileProfileIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/cart'
    | '/for-providers'
    | '/how-it-works'
    | '/provider'
    | '/account/favorites'
    | '/account/requests'
    | '/auth/login'
    | '/auth/register'
    | '/profile/$profileId'
    | '/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/cart'
    | '/for-providers'
    | '/how-it-works'
    | '/provider'
    | '/account/favorites'
    | '/account/requests'
    | '/auth/login'
    | '/auth/register'
    | '/profile/$profileId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/cart'
    | '/for-providers'
    | '/how-it-works'
    | '/provider'
    | '/account/favorites'
    | '/account/requests'
    | '/auth/login'
    | '/auth/register'
    | '/profile/$profileId'
    | '/services/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  ForProvidersRoute: typeof ForProvidersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ProviderRoute: typeof ProviderRoute
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountRequestsRoute: typeof AccountRequestsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProfileProfileIdRoute: typeof ProfileProfileIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-providers': {
      id: '/for-providers'
      path: '/for-providers'
      fullPath: '/for-providers'
      preLoaderRoute: typeof ForProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileId': {
      id: '/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof ProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/requests': {
      id: '/account/requests'
      path: '/account/requests'
      fullPath: '/account/requests'
      preLoaderRoute: typeof AccountRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/account/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  ForProvidersRoute: ForProvidersRoute,
  HowItWorksRoute: HowItWorksRoute,
  ProviderRoute: ProviderRoute,
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountRequestsRoute: AccountRequestsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProfileProfileIdRoute: ProfileProfileIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
